<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>Roslan.MvvmUtils.Blazor</PackageId>
    <Version>1.0.0</Version>
    <Title>MvvmUtils.Blazor</Title>
    <Company />
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <FileVersion>1.0.0</FileVersion>
    <NeutralLanguage>en</NeutralLanguage>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <Authors>Jan-Philipp Roslan</Authors>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MvvmUtils\MvvmUtils.csproj" />
  </ItemGroup>

</Project>
