<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <AssemblyName>Roslan.MvvmUtils.WinForms</AssemblyName>
    <RootNamespace>Roslan.MvvmUtils.WinForms</RootNamespace>
    <PackageId>Roslan.MvvmUtils.WinForms</PackageId>
    <Title>MvvmUtils.WinForms</Title>
    <Version>1.0.0</Version>
    <Authors>Jan-Philipp Roslan</Authors>
    <RepositoryType>git</RepositoryType>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <FileVersion>1.0.0</FileVersion>
    <NeutralLanguage>en</NeutralLanguage>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MvvmUtils\MvvmUtils.csproj" />
  </ItemGroup>

</Project>
